version: '3'

services:
  web:
    build:
      context: web
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: "mariadb:10.3"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example