version: '3'

services:
  web:
    build:
      context: web
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - "$TURINGWARS_CONFIG:/config"
  db:
    image: "mariadb:10.3"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - "$TURINGWARS_DATA:/var/lib/mysql"