version: '3'

services:
  web:
    restart: always
    build:
      context: web
    ports:
      - "$TURINGWARS_PORT:3000"
    links:
      - db
    volumes:
      - "$TURINGWARS_CONFIG:/config"
  db:
    image: "mariadb:10.3"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $TURINGWARS_DB_ROOT_PASSWORD
      MYSQL_USER: $TURINGWARS_DB_USER
      MYSQL_PASSWORD: $TURINGWARS_DB_PASSWORD
      MYSQL_DATABASE: $TURINGWARS_DB_DATABASE
    volumes:
      - "$TURINGWARS_DATA:/var/lib/mysql"